# Write your MySQL query statement below
SELECT ROUND(AVG(E.EXPERIENCE_YEARS),2) AS AVERAGE_YEARS , P.PROJECT_ID 
FROM PROJECT P INNER JOIN EMPLOYEE E ON P.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY P.PROJECT_ID